[project]
name = "hello-crew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai>=0.98.0",
    "crewai-tools>=0.32.1",
    "docling>=2.16.0",
    "langtrace-python-sdk>=3.5.0",
]

[project.scripts]
